CREATE DATABASE IF NOT EXISTS SHOPEE_MANAGEMENT_HOMEWORK;
USE SHOPEE_MANAGEMENT_HOMEWORK;
CREATE TABLE IF NOT EXISTS CATEGORY (
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCT (
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
PRICE DOUBLE NOT NULL DEFAULT 0 CHECK (PRICE >= 0),
CATEGORY_ID INT,
FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);

CREATE TABLE IF NOT EXISTS VARIANT (
ID INT AUTO_INCREMENT PRIMARY KEY,
COLOR VARCHAR(20) NOT NULL,
SIZE VARCHAR(10) NOT NULL,
PRODUCT_ID INT,
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);

CREATE TABLE IF NOT EXISTS CART (
ID INT AUTO_INCREMENT PRIMARY KEY,
TOTAL_PRICE DOUBLE
);

CREATE TABLE IF NOT EXISTS CUSTOMER (
ID INT AUTO_INCREMENT PRIMARY KEY,
USER_NAME VARCHAR(20) NOT NULL,
PASSWORD VARCHAR(15) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
PHONE_NUMBER VARCHAR(10) NOT NULL,
CART_ID INT UNIQUE,
FOREIGN KEY (CART_ID) REFERENCES CART(ID)
);

CREATE TABLE IF NOT EXISTS ADDRESS (
ID INT AUTO_INCREMENT PRIMARY KEY,
NUMBER INT,
STREET VARCHAR(100),
WARD VARCHAR(50) NOT NULL,
DISTRICT VARCHAR(50) NOT NULL,
PROVINCE VARCHAR(50) NOT NULL,
CUSTOMER_ID INT,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

CREATE TABLE IF NOT EXISTS CART_LINE_ITEM (
ID INT AUTO_INCREMENT PRIMARY KEY,
QUANTITY INT NOT NULL,
TOTAL_PRICE DOUBLE,
CART_ID INT,
VARIANT_ID INT,
FOREIGN KEY (CART_ID) REFERENCES CART(ID),
FOREIGN KEY (VARIANT_ID) REFERENCES VARIANT(ID)
);