CREATE DATABASE IF NOT EXISTS STUDENT_MANAGEMENT;
USE STUDENT_MANAGEMENT;
CREATE TABLE IF NOT EXISTS CLASS (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(60) NOT NULL,
    START_DATE DATETIME NOT NULL,
    STATUS BIT
);
CREATE TABLE IF NOT EXISTS STUDENT (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    ADDRESS VARCHAR(50),
    PHONE VARCHAR(20),
    STATUS BIT,
    CLASS_ID INT NOT NULL
);
CREATE TABLE IF NOT EXISTS SUBJECT (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    CREDIT TINYINT NOT NULL DEFAULT 1 CHECK (CREDIT >= 1),
    STUDENT_STATUS BIT DEFAULT 1
);
CREATE TABLE IF NOT EXISTS MARK (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SUBJECT_ID INT NOT NULL,
    STUDENT_ID INT NOT NULL,
    MARK FLOAT DEFAULT 0 CHECK (MARK BETWEEN 0 AND 100),
    EXAM_TIMES TINYINT DEFAULT 1,
    UNIQUE (SUBJECT_ID , STUDENT_ID),
    FOREIGN KEY (SUBJECT_ID)
        REFERENCES SUBJECT (ID),
    FOREIGN KEY (STUDENT_ID)
        REFERENCES STUDENT (ID)
);
