CREATE DATABASE IF NOT EXISTS quan_ly_vat_tu;
USE quan_ly_vat_tu;
CREATE TABLE IF NOT EXISTS SUPPLIER (
	ID INT AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(200) NOT NULL,
    PHONE_NUMBER VARCHAR(10) NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS THE_ORDER (
	ID INT AUTO_INCREMENT,
    ORDER_DATE DATETIME NOT NULL,
    SUPPLIER_ID INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(ID)
);
CREATE TABLE IF NOT EXISTS SUPPLIES (
	ID INT AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS THE_ORDER_LINE_ITEM (
	ID INT AUTO_INCREMENT,
    SUPPLIES_ID INT,
    THE_ORDER_ID INT,
    QUANTITY INT NOT NULL,
    TOTAL_PRICE DOUBLE NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (SUPPLIES_ID) REFERENCES SUPPLIES(ID),
    FOREIGN KEY (THE_ORDER_ID) REFERENCES THE_ORDER(ID)
);
CREATE TABLE IF NOT EXISTS IMPORT_INVOICE (
	ID INT AUTO_INCREMENT,
    DATE_IMPORT DATETIME NOT NULL,
    TOTAL_PRICE DOUBLE NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS IMPORT_INVOICE_LINE_ITEM (
	ID INT AUTO_INCREMENT,
    PRICE_IMPORT DOUBLE NOT NULL,
    QUANTITY_IMPORT INT NOT NULL,
    TOTAL_PRICE DOUBLE NOT NULL,
    IMPORT_INVOICE_ID INT,
    SUPPLIES_ID INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (IMPORT_INVOICE_ID) REFERENCES IMPORT_INVOICE(ID),
    FOREIGN KEY (SUPPLIES_ID) REFERENCES SUPPLIES(ID)
);
CREATE TABLE IF NOT EXISTS EXPORT_INVOICE (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    DATE_EXPORT DATETIME NOT NULL,
    TOTAL_PRICE DOUBLE NOT NULL
);
CREATE TABLE IF NOT EXISTS EXPORT_INVOICE_LINE_ITEM (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    PRICE_EXPORT DOUBLE NOT NULL,
    QUANTITY_EXPORT INT NOT NULL,
    TOTAL_PRICE DOUBLE NOT NULL,
    EXPORT_INVOICE_ID INT,
    SUPPLIES_ID INT,
    FOREIGN KEY (EXPORT_INVOICE_ID) REFERENCES EXPORT_INVOICE(ID),
    FOREIGN KEY (SUPPLIES_ID) REFERENCES SUPPLIES(ID)
);