CREATE DATABASE IF NOT EXISTS STUDENT_MANAGEMENT;
USE STUDENT_MANAGEMENT;
CREATE TABLE IF NOT EXISTS CLASS (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(60) NOT NULL,
    START_DATE DATETIME NOT NULL,
    STATUS BIT
);
CREATE TABLE IF NOT EXISTS STUDENT (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    ADDRESS VARCHAR(50),
    PHONE VARCHAR(20),
    STATUS BIT,
    CLASS_ID INT NOT NULL
);
CREATE TABLE IF NOT EXISTS SUBJECT (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    CREDIT TINYINT NOT NULL DEFAULT 1 CHECK (CREDIT >= 1),
    STUDENT_STATUS BIT DEFAULT 1
);
CREATE TABLE IF NOT EXISTS MARK (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SUBJECT_ID INT NOT NULL,
    STUDENT_ID INT NOT NULL,
    MARK FLOAT DEFAULT 0 CHECK (MARK BETWEEN 0 AND 100),
    EXAM_TIMES TINYINT DEFAULT 1,
    UNIQUE (SUBJECT_ID , STUDENT_ID),
    FOREIGN KEY (SUBJECT_ID)
        REFERENCES SUBJECT (ID),
    FOREIGN KEY (STUDENT_ID)
        REFERENCES STUDENT (ID)
);
-- INSERT INTO CLASS VALUES (1, "A1", "2008-12-20", 1);
-- INSERT INTO CLASS VALUES (2, "A2", "2008-12-22", 1);
-- INSERT INTO CLASS VALUES (3, "B3", current_date(), 0);
INSERT INTO STUDENT (NAME, ADDRESS, PHONE, STATUS, CLASS_ID)
VALUES ("Hung", "Ha Noi", "0912113113", 1, 1);
INSERT INTO STUDENT (NAME, ADDRESS, STATUS, CLASS_ID)
VALUES ("Hoa", "Hai Phong", 1, 1);
INSERT INTO STUDENT (NAME, ADDRESS, PHONE, STATUS, CLASS_ID)
VALUES ("Manh", "HCM", "0123123123", 0, 2);
INSERT INTO SUBJECT VALUES 
(1, "CF", 5, 1),
(2, "C", 6, 1),
(3, "HDJ", 5, 1),
(4, "RDBMS", 10, 1);
INSERT INTO MARK (SUBJECT_ID, STUDENT_ID, MARK, EXAM_TIMES) VALUES
(1, 1, 8, 1),
(1, 2, 10, 2),
(2, 1, 12, 1);
