CREATE DATABASE IF NOT EXISTS EXERCISE_LESSON_5;
USE EXERCISE_LESSON_5;
CREATE TABLE IF NOT EXISTS PRODUCT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(20),
    NAME VARCHAR(30) NOT NULL,
    PRICE DOUBLE NOT NULL,
    AMOUNT INT NOT NULL,
    DESCRIPTION VARCHAR(300),
    STATUS BIT
);
INSERT INTO PRODUCT (CODE, NAME, PRICE, AMOUNT, STATUS) VALUES
('QDA', 'Quần dài', 100000, 5, 1),
('QSH', 'Quần short', 150000, 3, 1),
('AT', 'Áo thun', 79000, 10, 1),
('ASM', 'Áo sơ mi', 119000, 7, 1),
('APL', 'Áo polo', 179000, 5, 1),
('SNP', 'Nón snapback', 95000, 5, 1),
('MK', 'Mắt kính', 50000, 5, 1);

ALTER TABLE PRODUCT ADD UNIQUE IDX_CODE (CODE);
ALTER TABLE PRODUCT ADD UNIQUE IDX_COMPOSITE (NAME, PRICE);
EXPLAIN SELECT * FROM PRODUCT WHERE CODE = "AT";
ALTER TABLE PRODUCT DROP INDEX IDX_CODE;


CREATE VIEW PRODUCT_VIEW AS
	SELECT
		CODE, NAME, PRICE, STATUS
	FROM
		PRODUCT;
SELECT * FROM PRODUCT_VIEW;
    
CREATE OR REPLACE VIEW PRODUCT_VIEW AS
	SELECT CODE, NAME, PRICE
	FROM PRODUCT;
SELECT * FROM PRODUCT_VIEW;
DROP VIEW PRODUCT_VIEW;


DELIMITER //
CREATE PROCEDURE GET_ALL()
	BEGIN
		SELECT * FROM PRODUCT;
	END // 
	DELIMITER ;
CALL GET_ALL();

DELIMITER //
CREATE PROCEDURE ADD_PRODUCT(
		IN NAME_OF_PRODUCT VARCHAR(30),
		IN PRICE_OF_PRODUCT DOUBLE, 
		IN AMOUNT_OF_PRODUCT INT)
    BEGIN
		INSERT INTO PRODUCT (NAME, PRICE, AMOUNT) VALUES 
        (NAME_OF_PRODUCT, PRICE_OF_PRODUCT, AMOUNT_OF_PRODUCT);
	END //
	DELIMITER ;
CALL ADD_PRODUCT("GIÀY", 2300000, 5);
CALL GET_ALL();

DELIMITER //
CREATE PROCEDURE EDIT_NAME_BY_ID(
		IN ID_PRODUCT INT,
        IN NEW_NAME VARCHAR(30))
	BEGIN
		UPDATE PRODUCT
			SET NAME = NEW_NAME
            WHERE ID = ID_PRODUCT;
	END //
	DELIMITER ;
CALL EDIT_NAME_BY_ID(1, "Quần Âu");
CALL GET_ALL();

DELIMITER //
CREATE PROCEDURE REMOVE_PRODUCT_BY_ID(IN ID INT)
	BEGIN
		DELETE FROM PRODUCT
			WHERE PRODUCT.ID = ID;
	END //
    DELIMITER ;
CALL REMOVE_PRODUCT_BY_ID(3);
