USE CLASSICMODELS;
CREATE VIEW CUSTOMER_VIEWS AS
    SELECT 
        CUSTOMERNUMBER, CUSTOMERNAME, PHONE
    FROM
        CUSTOMERS;
        
SELECT 
    *
FROM
    CUSTOMER_VIEWS;
    
CREATE OR REPLACE VIEW CUSTOMER_VIEWS AS
	SELECT
		CUSTOMERNUMBER, CUSTOMERNAME, CONTACTFIRSTNAME, CONTACTLASTNAME, PHONE
	FROM
		CUSTOMERS
	WHERE 
		CITY = "NANTES";

SELECT 
    *
FROM
    CUSTOMER_VIEWS;
    
DROP VIEW CUSTOMER_VIEWS;