USE CLASSICMODELS;
DELIMITER //
CREATE PROCEDURE getCusById (IN cusNum INT(11))
BEGIN
	SELECT * FROM CUSTOMERS WHERE CUSTOMERNUMBER = cusNum;
END // 
DELIMITER ;
CALL getCusById(175);

DELIMITER //
CREATE PROCEDURE GET_CUSTOMERS_COUNT_BY_CITY (IN IN_CITY VARCHAR(50), OUT TOTAL INT)
BEGIN
	SELECT COUNT(CUSTOMERNUMBER)
    INTO TOTAL
    FROM CUSTOMERS
    WHERE CITY = IN_CITY;
END //
DELIMITER ;
CALL GET_CUSTOMERS_COUNT_BY_CITY("LYON", @TOTAL);
SELECT @TOTAL;

DELIMITER //
CREATE PROCEDURE SET_COUNTER (INOUT COUNTER INT, IN INC INT)
BEGIN
	SET COUNTER = COUNTER + INC;
END //
DELIMITER ;
SET @COUNTER = 1;
CALL SET_COUNTER(@COUNTER, 1);
CALL SET_COUNTER(@COUNTER, 1);
CALL SET_COUNTER(@COUNTER, 5);
SELECT @COUNTER;