USE STUDENT_MANAGEMENT;
SELECT * FROM STUDENT WHERE STATUS = TRUE;
SELECT * FROM SUBJECT WHERE CREDIT < 10;
SELECT S.ID, S.NAME, C.NAME FROM STUDENT S JOIN CLASS C ON S.CLASS_ID = C.ID;
SELECT STUDENT.ID, STUDENT.NAME, CLASS.NAME 
FROM STUDENT JOIN CLASS ON STUDENT.CLASS_ID = CLASS.ID
WHERE CLASS.NAME ="A1";
SELECT S.ID, S.NAME, SUB.NAME, M.MARK
FROM STUDENT S JOIN MARK M ON S.ID = M.STUDENT_ID JOIN SUBJECT SUB ON M.SUBJECT_ID = SUB.ID;
SELECT S.ID, S.NAME, SUB.NAME, M.MARK
FROM STUDENT S JOIN MARK M ON S.ID = M.STUDENT_ID JOIN SUBJECT SUB ON M.SUBJECT_ID = SUB.ID
WHERE SUB.NAME = "CF";
SELECT * FROM STUDENT WHERE STUDENT.NAME LIKE "h%";
SELECT * FROM CLASS WHERE CLASS.START_DATE LIKE "_____12%";
SELECT * FROM SUBJECT WHERE SUBJECT.CREDIT BETWEEN 3 AND 5;
UPDATE STUDENT SET CLASS_ID = 2 WHERE NAME = "HUNG";
SELECT STUDENT.NAME, SUBJECT.NAME, MARK.MARK
FROM STUDENT JOIN MARK ON STUDENT.ID = MARK.STUDENT_ID JOIN SUBJECT ON MARK.SUBJECT_ID = SUBJECT.ID
ORDER BY MARK DESC, STUDENT.NAME ASC;
SELECT * FROM STUDENT;