USE STUDENT_MANAGEMENT;
SELECT * FROM STUDENT;
SELECT * FROM CLASS;
SELECT * FROM MARK;
SELECT * FROM SUBJECT;
SELECT * FROM STUDENT WHERE STATUS = TRUE;
SELECT * FROM SUBJECT WHERE CREDIT < 10;
SELECT S.ID, S.NAME, C.NAME FROM STUDENT S JOIN CLASS C ON S.CLASS_ID = C.ID;
SELECT STUDENT.ID, STUDENT.NAME, CLASS.NAME 
FROM STUDENT JOIN CLASS ON STUDENT.CLASS_ID = CLASS.ID
WHERE CLASS.NAME ="A1";
SELECT S.ID, S.NAME, SUB.NAME, M.MARK
FROM STUDENT S JOIN MARK M ON S.ID = M.STUDENT_ID JOIN SUBJECT SUB ON M.SUBJECT_ID = SUB.ID;
SELECT S.ID, S.NAME, SUB.NAME, M.MARK
FROM STUDENT S JOIN MARK M ON S.ID = M.STUDENT_ID JOIN SUBJECT SUB ON M.SUBJECT_ID = SUB.ID
WHERE SUB.NAME = "CF";