CREATE DATABASE PRACTICE_JDBC_LS12;
USE PRACTICE_JDBC_LS12;
CREATE TABLE USERS (
    ID INT(3) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(120) NOT NULL,
    EMAIL VARCHAR(220) NOT NULL,
    COUNTRY VARCHAR(120)
);
INSERT INTO USERS(NAME, EMAIL, COUNTRY) VALUES
("MINH", "MINH@GMAIL.COM", "VIET NAM"),
("KANTE", "KANTE@GMAIL.COM", "KENIA");
SELECT * FROM USERS;